### ISSUE TITLE
Summit Crab stops destroying

### ISSUE THREAD

**Issue by firefoxpdm** [juanosarg/AlphaAnimals#13]
A Summit Crab appeared with chronic kidney disease (also alzheimer's, dementia, congenital heart defect, artery blockade, asthma, bad back and cataract on both eyes... man, was it messed up). It started destroying the area in a nice straight line. Then it threw up, and started grazing around like any normal animal: no more destruction, no more killing.

It should have continued its rampage even after the sickness event kicked in.

**Comment by juanosarg** [comment]
I'm kinda ok with this one :) Once downed, the summit crabs stop doing damage. Poor thing, he was just an old fart
