### ISSUE TITLE
log error appears multiple times in gameplay

### ISSUE THREAD

**Issue by Translator5** [juanosarg/AlphaAnimals#3]
this error appears sometimes mid-game

``
Couldn't find AA_Groundrunner_SkinSet.xml! This file is required for animals using the variations framework.
Verse.Log:Error(String, Boolean)
AnimalVariations.AnimalMultiSkins:SpawnSetup(Map, Boolean)
Verse.GenSpawn:Spawn(Thing, IntVec3, Map, Rot4, WipeMode, Boolean)
Verse.GenSpawn:Spawn(Thing, IntVec3, Map, WipeMode)
RimWorld.WildAnimalSpawner:SpawnRandomWildAnimalAt(IntVec3)
RimWorld.WildAnimalSpawner:WildAnimalSpawnerTick()
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
``

how to fix, what to do?

**Comment by Translator5** [comment]
Got it!
File "AA_Groundrunner_SkinSet.xml" does not exist in the path.
There is a "AA_GroundRunner_SkinSet.xml" ... Linux case-sensibility :laughing: . 
Renaming it or making a copy of them with various names fix this issue.

**Comment by juanosarg** [comment]
This was caused by GitHub not keeping uppercase when it should. It was fixed a while ago, but GitHub will break it again one day
