### ISSUE TITLE
Would you please provide CE compatibility?

### ISSUE THREAD

**Issue by jinlan** [juanosarg/AlphaAnimals#5]
There is already a project doing that. But it's a long time scene its last update. CE has already dramatically changed. And AA also has many new stuff. So, please. 

https://github.com/Saebbi/Alpha-Animals-CE-Patch

**Comment by brucethemoose** [comment]
+1 

I'm not sure what ya'll know/remember about CE. I wasn't a CE fan in previous versions of Rimworld, but the latest version addresses most of the complaints I had. It's a great overhaul now, and plays nice with far more mods than it used to thanks to built-in harmony patching.

**Comment by brucethemoose** [comment]
Regenerating Avoidgrids with RuntimeGC seemingly fixes the log spam, but destroying all things on the map in dev mode does not.

**Comment by juanosarg** [comment]
CE is poop
